
- name: crate config file
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job.xml
    
- name: create jobs
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/job.xml') }}"
    name: test
    url: http://172.31.1.32:8080
    user: admin
    password: "{{jenkinspassword}}"
  loop: -frontend -cart -catalogue
