- name: create folders
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/job.xml') }}"
    name: "{item}"
    url: http://172.31.1.32:8080
    user: admin
    password: "{{jenkinspassword}}"
    loop:
     - CIPipelines
  


- name: Apply tags to tasks within included file
  ansible.builtin.include_tasks:
    file: pipeline.yml
  loop:
   - {name: "frontend", dir: "CIPipelines"}
  
   