- name: Create Folder
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    #url: http://172.31.15.144:8080
    url: http://172.31.9.181:8080

    
    user: admin
    password: "{{jenkinspassword}}"
  loop: "{{ folders }}"
  
- name: Create Multibranch Pipeline Jobs
  ansible.builtin.include_tasks: mbranch-pipeline.yml
  loop: "{{ ci_pipeline_jobs}}"
  
- name: Create single Pipeline Jobs
  ansible.builtin.include_tasks: sbranch-pipeline.yml
  loop: "{{ sbranch_pipeline_jobs }}"






   