
- name: crate config file
  ansible.builtin.template:
    src: s_job.xml
    dest: /tmp/s_job.xml
    
- name: create jobs
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/s_job.xml') }}"
    name: "{item}"
    url: http://172.31.1.32:8080
    user: admin
    password: "{{jenkinspassword}}"
  
