- name: Create Config file
  ansible.builtin.template:
    src: s-job.xml
    dest: /tmp/s-job.xml

- name: Create Job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/s-job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    #url: http://172.31.15.144:8080
    url: http://172.31.9.181:8080
         

    user: admin
    password: "{{jenkinspassword}}"
    